### ISSUE TITLE
laravel 5.1

### ISSUE THREAD

**Issue by sixty8** [themsaid/laravel-mail-preview#14] opened 2016-05-28 16:08 UTC
Driver [preview] not supported.

**Comment by mgufrone** [comment] 2016-06-29 21:28
+1 I got the same error

**Comment by themsaid** [comment] 2016-07-14 11:02
Can you please confirm it was fixed in v1.2.4 ?

**Comment by mgufrone** [comment] 2016-07-15 07:27
it doesn't show exception any more, but it doesn't generate any files inside the specified output directory. (my output directory is storage/email-previews as this package suggested)

**Comment by Braunson** [comment] 2017-02-13 21:23
I'm receiving this in 5.4, using ^1.2 ...

**Comment by themsaid** [comment] 2017-02-14 08:29
@braunson I don't seem to be able to replicate, can you please double check the installation instruction?

**Comment by Braunson** [comment] 2017-02-14 17:40
@themsaid Sorry, figured it out, had to `composer-dumpautoload` and it was caused by an error from another package. Working on 5 .4 :)

**Closed** 2017-06-29 17:36 UTC
